image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: cargo test --no-run # Prebuild tests
    init: cd website && npm install && NODE_ENV=development npx tailwindcss -i index.css -o ./static/tailwind.css --jit && trunk build # Prebuild website

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
