[package]
name = "sycamore-reactive-macro"
categories = ["gui", "wasm", "web-programming"]
description = "Reactive primitives for Sycamore"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.9.0-beta.1"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.60"
syn = "2.0.18"
quote = "1.0.28"
