[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "if [ ! -e tailwind.css ]; then touch tailwind.css; fi"]

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "tailwindcss -mo tailwind.css"]
