[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "if [ ! -e tailwind.css ]; then touch tailwind.css; fi"]

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "if command -v tailwindcss; then tailwindcss -mo tailwind.css; else echo Warning: tailwindcss executable not found; fi"]
