[package]
name = "sycamore-web2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13.2"
html-escape = { version = "0.2.13", optional = true }
indexmap = "1.9.2"
js-sys = "0.3.60"
once_cell = "1.17.0"
sycamore-core2 = { version = "0.1.0", path = "../sycamore-core2" }
sycamore-futures = { version = "0.8.0", path = "../sycamore-futures", optional = true }
sycamore-reactive = { version = "0.8.1", path = "../sycamore-reactive" }
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "console",
    "Comment",
    "Document",
    "DocumentFragment",
    "DomTokenList",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlCollection",
    "Node",
    "NodeList",
    "Text",
    "Window",
    # Events
    "AnimationEvent",
    "BeforeUnloadEvent",
    "CompositionEvent",
    "DeviceMotionEvent",
    "DeviceOrientationEvent",
    "DragEvent",
    "ErrorEvent",
    "Event",
    "FocusEvent",
    "GamepadEvent",
    "HashChangeEvent",
    "InputEvent",
    "KeyboardEvent",
    "MessageEvent",
    "MouseEvent",
    "PageTransitionEvent",
    "PointerEvent",
    "PopStateEvent",
    "ProgressEvent",
    "PromiseRejectionEvent",
    "SecurityPolicyViolationEvent",
    "StorageEvent",
    "SubmitEvent",
    "TouchEvent",
    "TransitionEvent",
    "WheelEvent",
]

[features]
default = ["dom"]
dom = []
hydrate = ["sycamore-core2/hydrate"]
ssr = ["hydrate", "html-escape"]
suspense = ["sycamore-futures"]

silence_dom_ssr_features_error = []
