[package]
name = "sycamore-core2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13.1"
sycamore-futures = { path = "../sycamore-futures", version = "0.8.0", optional = true }
sycamore-reactive = { path = "../sycamore-reactive", version = "0.8.1" }

[dev-dependencies]
sycamore = { path = "../sycamore", features = ["ssr"] }
