[build]
no_minification = true # Disable minification for this example since it interferes with hydration.

[watch]
ignore = ["index.html"]

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["run"]
