#!/bin/bash

echo Installing Rust with wasm32-unknown-unknown target

rustup toolchain install stable
rustup target add wasm32-unknown-unknown 

cargo install trunk --version ^0.10.0

cargo install wasm-bindgen-cli --version ^0.2.73


cd ./docs
trunk build --release

cd ..

output="$(pwd)/docs/dist"

mkdir "$output/example"

for path in examples/*; do
    if [[ ! -d $path ]]; then
    continue
    fi
    example=$(basename "$path")

    echo "building: $example"
    (
    cd "$path"
    dist_dir="$output/example/$example"
    mkdir "$dist_dir"
    trunk build --release --dist "$dist_dir" --public-url "/example/$example"
    )
done
