[package]
name = "js-framework-benchmark"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
rand = "0.10.3"
sycamore = { path = "../../packages/sycamore" }

[lints]
workspace = true
